nodeLinker: node-modules
packageExtensions:
  "@silverstripe/eslint-config@*":
    peerDependencies:
      "eslint-plugin-react-hooks": "^5.2.0"
      "postcss": "^8.4.21"
      "webpack": "^5.74.0"
    peerDependenciesMeta:
      "eslint-plugin-react-hooks":
        optional: true
      "postcss":
        optional: true
      "webpack":
        optional: true